---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  namespace: development
spec:
  selector:
    matchLabels:
      app: todo-api
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api 
        image: yolix/todo-api:v1
        ports:
        - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: todo-api-lb
  namespace: development
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3001
  selector:
    app: todo-api